name: common-npm-publish

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        default: 22.x
      working-directory:
        required: false
        type: string
        default: .
    secrets:
      npm-token:
        required: true

permissions:
  contents: read

jobs:
  publish:
    if: github.event_name == 'release' && github.event.release.action == 'published'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          registry-url: https://registry.npmjs.org
      - run: npm ci
      - run: npm test
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm-token }}
